steps:
#Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACTORY_NAME/$REPO_NAME:$COMMIT_SHA'
    - '-t'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACTORY_NAME/$REPO_NAME:latest'
    - '.'
#Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACTORY_NAME/$REPO_NAME'
    - '--all-tags'